# Generated by Django 5.2.5 on 2025-10-08 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'INSTITUCION',
            },
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fase', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'RONDA',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'SALA',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('visitante', 'visitante'), ('otro', 'otro')], default='visitante', max_length=20)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appTorneos.institucion')),
            ],
            options={
                'db_table': 'EQUIPO',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150)),
                ('rol', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.equipo')),
            ],
            options={
                'db_table': 'PARTICIPANTE',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('posicion', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.equipo')),
            ],
            options={
                'db_table': 'RANKING',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganadas', to='appTorneos.equipo')),
                ('equipo_perdedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perdidas', to='appTorneos.equipo')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.ronda')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.sala')),
            ],
            options={
                'db_table': 'RESULTADO',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_equipo', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.equipo')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.ronda')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.sala')),
            ],
            options={
                'db_table': 'ASIGNACION',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cambio', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.usuario')),
            ],
            options={
                'db_table': 'HISTORIAL',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.usuario')),
            ],
            options={
                'db_table': 'BACKUP',
            },
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.participante')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.ronda')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTorneos.sala')),
            ],
            options={
                'db_table': 'PUNTAJE',
                'unique_together': {('participante', 'sala', 'ronda')},
            },
        ),
    ]
