# Generated by Django 5.2.5 on 2025-10-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTorneos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='puntaje_total',
            new_name='puntajetotal',
        ),
    ]
