# Generated by Django 5.2.7 on 2025-11-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTorneos', '0002_rename_puntaje_total_ranking_puntajetotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
