# Generated by Django 5.2.7 on 2025-11-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTorneos', '0003_usuario_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
